# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Food Oasis Los Angeles
email: fooddesertsla@gmail.com
description: This website was put together during the Civic Hack Nights at hackforla.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foodoasis.la" # the base hostname & protocol for your site
github_username: foodoasisla
permalink: pretty

# These files are unique to the “site” repository.
exclude:
    - rakefile

# These files are unique to the “foodoasisla.github.io” repository.
keep_files:
    - .nojekyll
    - .gitignore
    - .git
